# Generated by Django 4.2.7 on 2024-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_voluteer',
            field=models.BooleanField(default=False),
        ),
    ]
