# Generated by Django 4.2.7 on 2024-03-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_is_voluteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_voluteer',
        ),
    ]
