# Generated by Django 4.2.7 on 2024-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
